### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by micaiah-effiong** [micaiah-effiong/url-shortener#18]
Create a readme that helps contributors to effectively contribute to the project

**Comment by alexrobaina** [comment]
Hi @micaiah-effiong, I can work in this issue. Would you like to assign me the issue?

**Comment by micaiah-effiong** [comment]
@alexrobaina you're free to jump on it... ✌️✌️

**Comment by micaiah-effiong** [comment]
While writing the documentation, remember to keep it as simple as possible and yet informative.

The technologies used are:

- Nodejs
- Express
- MongoDB (mongoose)
- Vue

**Comment by alexrobaina** [comment]
Ok, I'm going run the project in my localhost and read the documentations for create a nice document.
