### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by micaiah-effiong** [micaiah-effiong/url-shortener#22]
The project also needs a corresponding login page to sign-in users

**Comment by sreejithvs333** [comment]
Hi, @micaiah-effiong I would love to work on this issue. Unfortunately, It seems the Figma design link provided is not public.

**Comment by micaiah-effiong** [comment]
@sreejithvs333 okay I'll make it public, so you can work on it...

**Comment by sreejithvs333** [comment]
Yes..please. Also please add the topic "hacktoberfest". I am participating in it. Please see https://hacktoberfest.digitalocean.com/hacktoberfest-update.

**Comment by sreejithvs333** [comment]
Still can't access it. Please see the picture. This is what I see.

<img width="1334" alt="Screenshot 2020-10-03 at 5 27 15 PM" src="https://user-images.githubusercontent.com/8237812/94991004-cbac4080-059d-11eb-945e-4c6459bff82f.png">

**Comment by micaiah-effiong** [comment]
@sreejithvs333 the link has been made public, you can follow the link to start design...

**Comment by micaiah-effiong** [comment]
> Yes..please. Also please add the topic "hacktoberfest". I am participating in it. Please see https://hacktoberfest.digitalocean.com/hacktoberfest-update.

Not to worry @sreejithvs333 , once you make a pull request, ```hacktoberfest``` will detect it, according to them the label is not necessary, it only to help contributors find open source projects easily.
Just be sure to register on ```hacktoberfest``` and allow access to your git profile.
Good luck

**Comment by sreejithvs333** [comment]
Yes, I have access to Figma design now. Working on it.
But please see the screenshot below. Now it's required to add a topic in about section of the project. Please consider doing that. I will create PR once the page is done.

Check this link please: https://hacktoberfest.digitalocean.com/hacktoberfest-update

<img width="1341" alt="Screenshot 2020-10-03 at 9 35 50 PM" src="https://user-images.githubusercontent.com/8237812/94996312-88fc5f80-05c1-11eb-9767-41b4a5fcfd12.png">

**Comment by micaiah-effiong** [comment]
> Yes, I have access to Figma design now. Working on it.
> But please see the screenshot below. Now it's required to add a topic in about section of the project. Please consider doing that. I will create PR once the page is done.
> 
> Check this link please: https://hacktoberfest.digitalocean.com/hacktoberfest-update
> 
> <img alt="Screenshot 2020-10-03 at 9 35 50 PM" width="1341" src="https://user-images.githubusercontent.com/8237812/94996312-88fc5f80-05c1-11eb-9767-41b4a5fcfd12.png">

Inline with the updated requirements for ```hacktoberfest``` the repo now has a ```hacktoberfest``` topic and label...

@sreejithvs333 thanks for the update

**Comment by sreejithvs333** [comment]
Hi, @micaiah-effiong  I'm a little confused here as there is no View route is defined.

Few questions: 

1. I saw only Express router. Can I serve the HTML file statically?
2. Did you used Vue CLI?
3. I am basically a developer where I assumed this issue is for coding the login page. As I couldn't find the design for the login page, are you expecting someone to do graphic design?
4. If you are expecting to code and since I saw only the design for the home page in Figma, Is it okay if I code my own design for the login page by inspiring from the home page look and feel?

Could you please include a sample "login works" page with routing enabled? So that I can work on the View part. Let me know!

**Comment by micaiah-effiong** [comment]
1. Use HTML.
2. No, but we will use Vue when the time comes.
3. The figma design was made by a contributor and as such did not create a full UI as you would have expected.
4. So, it is okay if you code a login from the Homepage "look and feel".

Thanks.
Always remember, your contributions are greatly appreciated
