### ISSUE TITLE
Animation

### ISSUE THREAD

**Issue by Emilsone** [micaiah-effiong/url-shortener#3]
There are many advantages of including animation in web design. It keeps your visitors on your site longer so your bounce rate is lower. This means that your visitors may be staying on your page longer. It increases the level of interest in your site and encourages more shares and revisits.

**Comment by micaiah-effiong** [comment]
> There are many advantages of including animation in web design. It keeps your visitors on your site longer so your bounce rate is lower. This means that your visitors may be staying on your page longer. It increases the level of interest in your site and encourages more shares and revisits.

Wouldn't the animation lead to the page loading slowly...

Remember speed is always a user experience issue

**Comment by micaiah-effiong** [comment]
If the animation is still necessary, then let's have it so we can close this issue and focus on other things

**Comment by Emilsone** [comment]
Animation not necessary for now
